### PR TITLE
Added capability for Command Line Arguments / CSP w/ wahoo Extension for SetTarget wattage + Speed Broadcasting

### PR DESCRIPTION
**Pull request by mjunkmyjunk**
Added command line arguments to accept/detemrine which services are to be offered and what data to be broadcasted (only applicable to the CSP profile)

Applied the SetTarget capability to receive command from test apps indicating a change in Wattage target has been received. This is based on an extension to the CSP profile used by Wahoo.

Added capability to broadcast speed data into the CSP profile.

(Note: Using the CSP profile with power/cadence/speed will have caveats.)

### CODE REVIEW

**Comment by paixaop** [comment]
thanks!

**Comment by mjunkmyjunk** [comment]
Thanks for integrating it. I do need help however.

for this(these) line of code - https://github.com/paixaop/zwack/blob/0abecc5f049770d3ac37d4a3212abaf50794b994/lib/zwack-ble-sensor.js#L78

How can I "build" only specific services to be advertised? I tried various methods ( this is my 1st time dabbling in node.js :-p) and wasn't successful to build the array much like how I build the array based on the command line arguments.

**Comment by paixaop** [comment]
first thank you for your contribution.
It's easy just 'push' the element to the array

```
 // Selectively build the array of Services which we offer/broadcast
 if ( containsFTMS ) { servicesOfferedArray.push('1826') }
 if ( containsCSP ) { servicesOfferedArray.push('1818') }
 if ( containsRSC ) { servicesOfferedArray.push('1814') }
```
Generally speaking tough it's not good practice to have command line parsing inside an object class such as `ZwackBLE`. that leads to *MANY* issues down stream where you're using the class outside the scope of a command line application.
So the best course of action would be to parse the command line args in `simulator.js` then pass these in the options to `ZwackBLE` constructor [here](https://github.com/paixaop/zwack/blob/0abecc5f049770d3ac37d4a3212abaf50794b994/example/simulator.js#L50)

```
var zwackBLE = new ZwackBLE({ 
   name: sensorName,
   modelNumber: 'ZW-101',
   serialNumber: '1',
   ftms: containsFTMS,
   csp: containsCSP,
   rsc: constainRSC
});
```
then on the [class](https://github.com/paixaop/zwack/blob/0abecc5f049770d3ac37d4a3212abaf50794b994/lib/zwack-ble-sensor.js#L46) check the options:

```
constructor(options) {
    super();
    this.name = options.name || "Zwack";
    options.ftms = options.ftms || true; // default is enabled
    options.csp = options.csp || true; // default is enabled
    options.rsc = options.rsc || true; // default is enabled

    process.env['BLENO_DEVICE_NAME'] = this.name;

    if(options.csp) {
        this.csp = new CyclingPowerService();
    }
    if(options.rsc) {
        this.rsc = new RSCService();
    }
    if(options.ftms) {
        this.ftms = new FTMSService();
    }
< ... rest of the code ... >
```

but then you need to add the necessary checks for `undefined` `this.ftms`, `this.rsc`, and `this.rsc` throughout the rest of the class' methods .

**Comment by mjunkmyjunk** [comment]
Thank you for your guidance. Appreciate the fact that should not touch the class. In lack of a better word, it's boils down to "I didn't know how to pass the options" hence that method. (I will change it to below per your guidance)

Note that I used the [servicesOfferedUUIDArray.length] as for x reason, using .push didn't work (Searching SO, it talked about possibly it was an async operation but somehow I doubt that since this is not a loop)

```
this.dis = new DeviceInformationService(options);
if ( options.csp  ) { 
	this.csp = new CyclingPowerService(); 
	servicesOfferedUUIDArray[servicesOfferedUUIDArray.length] = '1818';
} else {
	this.csp = new DeviceInformationService(options);
}
if ( options.rsc  ) { 
	this.rsc = new RSCService(); 
	servicesOfferedUUIDArray[servicesOfferedUUIDArray.length] = '1814';
} else {
this.rsc = new DeviceInformationService(options);
}
if ( options.ftms ) { 
	this.ftms = new FTMSService(); 
	servicesOfferedUUIDArray[servicesOfferedUUIDArray.length] = '1826';
} else {
	this.ftms = new DeviceInformationService(options);
}
```

also  I had trouble w/ the below `setServices` - in the end, I tried using the default of just putting in the ` new DeviceInformationService(options);` instead which seems to work but I'm sure is not ideal.

```
if (!error) {
bleno.setServices(
[
	self.dis,
	self.csp,
	self.rsc,
	self.ftms
], 
```

with regard to your comment about

> but then you need to add the necessary checks for undefined this.ftms, this.rsc, and this.rsc throughout the rest of the class' methods .

I believe you meant these lines? or the `setServices` lines above? (then yes, these are the one I'm having issue w)
```
this.ftms.notify(event);
this.rsc.notify(event);
this.csp.notify(event);
```

but wouldn't these _not_ matter since the command line options would have removed these functions from being called?

Again, thank you for your guidance.

**Pull request merged**
